/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.pwdhashandroid;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int app_sample_code=0x7f020000;
        public static final int icon=0x7f020001;
    }
    public static final class id {
        public static final int buttonCopyAndOpen=0x7f050004;
        public static final int buttonCopyClip=0x7f050003;
        public static final int buttonCreateShortcut=0x7f050005;
        public static final int editTextSiteDomain=0x7f050001;
        public static final int editTextSitePassword=0x7f050002;
        public static final int txt_shortcut_intent=0x7f050000;
    }
    public static final class layout {
        public static final int launcher_shortcuts=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int copy_clipboard=0x7f040004;
        public static final int copy_clipboard_visit_site=0x7f040005;
        public static final int create_shortcut=0x7f040006;
        public static final int hello=0x7f040000;
        public static final int label_intent=0x7f040008;
        public static final int lable_site_domain=0x7f040002;
        public static final int lable_site_password=0x7f040003;
        public static final int msg_launcher_shortcuts=0x7f040009;
        public static final int sample_shortcuts=0x7f04000b;
        public static final int shortcut_name=0x7f040007;
        public static final int shortcuts=0x7f04000a;
    }
}
